[option]
exclude_paths = []
indent = 2
prefix_inout = "b_"
prefix_input = "i_"
prefix_output = "o_"
prefix_label = "l_"
prefix_instance = "u_"
prefix_module = "mod_"
prefix_package = "pkg_"
prefix_interface = "ifc_"

[textrules]
header_copyright = true
style_directives = false
style_semicolon  = true

[rules]
blocking_assignment_in_always_ff = true
case_default = true
default_nettype_none = true
enum_with_type = true
explicit_case_default = true
explicit_if_else = true
for_with_begin = true
function_same_as_system_function = false
function_with_automatic = false
generate_case_with_label = false
generate_for_with_label = false
generate_if_with_label = false
generate_keyword_forbidden = false
generate_keyword_required = false
genvar_declaration_in_loop = false
genvar_declaration_out_loop = true
if_with_begin = false
inout_with_tri = false
input_with_var = false
interface_port_with_modport = true
legacy_always = false
level_sensitive_always = false
localparam_explicit_type = true
localparam_type_twostate = false
loop_variable_declaration = false
lowercamelcase_interface = false
lowercamelcase_module = false
lowercamelcase_package = false
non_ansi_module = false
non_blocking_assignment_in_always_comb = false
output_with_var = false
parameter_explicit_type = false
parameter_in_package = false
parameter_type_twostate = false
prefix_inout = false
prefix_input = true
prefix_instance = false
prefix_interface = false
prefix_module = false
prefix_output = true
prefix_package = false
priority_keyword = false
sequential_block_in_always_comb = false
sequential_block_in_always_ff = false
sequential_block_in_always_latch = false
style_commaleading = false
style_indent = false
style_keyword_0or1space = false
style_keyword_0space = false
style_keyword_1or2space = false
style_keyword_1space = false
style_keyword_construct = false
style_keyword_datatype = false
style_keyword_end = false
style_keyword_maybelabel = false
style_keyword_newline = false
tab_character = false
unique0_keyword = false
unique_keyword = false
uppercamelcase_interface = true
uppercamelcase_module = true
uppercamelcase_package = true
wire_reg = false
